---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - '*'
    schedule:
      interval: monthly
    commit-message:
      prefix: deps(github-actions)

  - package-ecosystem: npm
    directory: /
    groups:
      astro-packages:
        patterns:
          - '@astrojs/*'
          - '@astrolib/*'
          - astro
          - astro-*
        dependency-type: production
      prod-deps:
        exclude-patterns:
          - '@astrojs/*'
          - '@astrolib/*'
          - astro
          - astro-*
        dependency-type: production
      dev-deps:
        dependency-type: development
    schedule:
      interval: monthly
    commit-message:
      prefix: deps(prod)
      prefix-development: deps(dev)
